/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [CorporateDB]    Script Date: 9/8/2021 9:21:16 PM ******/
CREATE DATABASE [CorporateDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CorporateDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CorporateDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CorporateDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CorporateDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CorporateDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CorporateDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CorporateDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CorporateDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CorporateDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CorporateDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CorporateDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CorporateDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CorporateDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CorporateDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CorporateDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CorporateDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CorporateDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CorporateDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CorporateDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CorporateDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CorporateDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CorporateDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CorporateDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CorporateDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CorporateDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CorporateDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CorporateDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CorporateDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CorporateDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CorporateDB] SET  MULTI_USER 
GO

ALTER DATABASE [CorporateDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CorporateDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CorporateDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CorporateDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CorporateDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CorporateDB] SET QUERY_STORE = OFF
GO

USE [CorporateDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CorporateDB] SET  READ_WRITE 
GO

